# -*- coding: utf-8 -*-
"""Project 7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xz36WvfhQ-eGypcwHLie125rNhmPrxM7
"""

import streamlit as st
import tensorflow as tf
import numpy as np
from PIL import Image

# -----------------------------
# Page Configuration
# -----------------------------
st.set_page_config(
    page_title="Male & Female Image Classifier",
    page_icon="🧑",
    layout="centered"
)

st.title("🧑 Male & Female Image Classifier")
st.write("Upload an image to predict whether it is **Male** or **Female**.")

# -----------------------------
# Load Model
# -----------------------------
@st.cache_resource
def load_my_model():
    model = tf.keras.models.load_model("binary_image_classifier.h5")
    return model

model = load_my_model()

# -----------------------------
# Image Preprocessing Function
# -----------------------------
IMG_SIZE = (150, 150)

def preprocess_image(img):

    img = img.resize(IMG_SIZE)
    img = img.convert("RGB")

    img_array = np.array(img)

    img_array = img_array / 255.0

    img_array = np.expand_dims(img_array, axis=0)

    return img_array

# -----------------------------
# File Upload
# -----------------------------
uploaded_file = st.file_uploader(
    "Upload Image",
    type=["jpg", "jpeg", "png"]
)

if uploaded_file is not None:

    image = Image.open(uploaded_file)

    st.image(image, caption="Uploaded Image", use_container_width=True)

    input_image = preprocess_image(image)

    prediction = model.predict(input_image)

    probability = prediction[0][0]

    if probability >= 0.5:
        label = "👨 Male"
        confidence = probability * 100
    else:
        label = "👩 Female"
        confidence = (1 - probability) * 100

    st.success(f"Prediction: **{label}**")

    st.info(f"Confidence: **{confidence:.2f}%**")

    st.write("Raw Prediction Value:", float(probability))