# -*- coding: utf-8 -*-
"""Project 7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xz36WvfhQ-eGypcwHLie125rNhmPrxM7
"""
import streamlit as st
import numpy as np
from PIL import Image

try:
    from tflite_runtime.interpreter import Interpreter
except ImportError:
    st.error("tflite-runtime is not installed.")
    st.stop()

st.set_page_config(
    page_title="Male & Female Image Classifier",
    page_icon="♂️♀️",
    layout="centered"
)

st.title("♂️♀️ Male & Female Image Classifier")
st.write("Upload an image to predict whether it is **Male** or **Female**.")

@st.cache_resource
def load_model():
    interpreter = Interpreter(model_path="binary_image_classifier_float16.tflite")
    interpreter.allocate_tensors()
    return interpreter

interpreter = load_model()

input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

IMG_SIZE = (150, 150)

def preprocess_image(img):
    img = img.convert("RGB")
    img = img.resize(IMG_SIZE)

    img = np.array(img, dtype=np.float32)
    img = img / 255.0
    img = np.expand_dims(img, axis=0)

    return img

uploaded_file = st.file_uploader(
    "Upload Image",
    type=["jpg", "jpeg", "png"]
)

if uploaded_file is not None:

    image = Image.open(uploaded_file)

    st.image(image, caption="Uploaded Image", use_container_width=True)

    input_data = preprocess_image(image)

    interpreter.set_tensor(input_details[0]["index"], input_data)
    interpreter.invoke()

    prediction = interpreter.get_tensor(output_details[0]["index"])

    probability = float(prediction[0][0])

    if probability >= 0.5:
        label = "♂️ Male"
        confidence = probability * 100
    else:
        label = "♀️ Female"
        confidence = (1 - probability) * 100

    st.success(f"Prediction: {label}")
    st.info(f"Confidence: {confidence:.2f}%")
